name: AuthMe demo
main: ch.jalu.authme.integrationdemo.SamplePlugin
version: 0.1
softdepend:
    - AuthMe
commands:
    firesword:
        description: Toggles the fire sword feature for the given player
        usage: '/firesword [player]'
    exists:
        description: Checks if a username is registered in AuthMe
        usage: '/exists <name>'